## Introduction to Pandas
### What's pandas?
 - Pandas is an open source library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. <br>
 - Pandas is part of the Anaconda distribution and can be installed with Anaconda (e.g. <code> conda install pandas </code>) or via pip (<code> pip install pandas</code>) <br>
 - When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool (assuming not so large files). <br>
 - Pandas help us to explore, clean, and process our data. <br>
 - In pandas, a data table is called a DataFrame.  <br>
<img src="https://pandas.pydata.org/pandas-docs/stable/_images/01_table_dataframe.svg" width="600">

 - Pandas supports the integration with many file formats or data sources out of the box (csv, excel, sql, json, parquet,…). Importing data from each of these data sources is provided by function with the prefix <span style="color: red;">read_*</span>. Similarly, the <span style="color: red;">to_*</span> methods are used to store data <br> [e.g. <code> sales = pd.read_csv("sales_data.csv" </code>) ] <br>
<img src="https://pandas.pydata.org/pandas-docs/stable/_images/02_io_readwrite.svg" width="800">

Before working with different datasets, let's learn the basics.

<b> Note: </b> Make sure that you have/installed pandas and openpyxl before we proceed. <br>
Once again, you can use the terminal <br>
<code> conda install pandas </code> <br>
and <br>
<code> conda install -c anaconda openpyxl </code> 
<br>
If you don't use conda, then <br>
<code> pip install pandas  </code> <br>
<code> pip install openpyxl </code> 
<br>
<b> Note: </b> We will work on time series / date functionality later. <br>
In the meantime, you can start learning about them at <br>
https://pandas.pydata.org/docs/user_guide/timeseries.html <br>
https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases

In [1]:
import pandas as pd
import numpy as np

### Object Creation

In [2]:
# Creating a Series by passing a list of values, 
# letting pandas create a default integer index:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [ ]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
# Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:
dates = pd.date_range('20220101', periods=6)

In [4]:
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')

Let's use dates as our index

In [5]:
df = pd.DataFrame(np.random.randint(1,11, size=(6, 4)), index=dates, columns=list('ABCD'))

In [6]:
df

            A  B   C   D
2022-01-01  8  6  10   2
2022-01-02  9  8   1   7
2022-01-03  3  9   3   1
2022-01-04  6  3   9   7
2022-01-05  1  1   1   2
2022-01-06  2  5   9  10

In [7]:
# Creating a DataFrame by passing a dict of objects that can be converted to series-like.
# Note how we create the index and column names
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20220218'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})

In [8]:
df2

     A          B    C  D      E    F
0  1.0 2022-02-18  1.0  3   test  foo
1  1.0 2022-02-18  1.0  3  train  foo
2  1.0 2022-02-18  1.0  3   test  foo
3  1.0 2022-02-18  1.0  3  train  foo

In [9]:
# The columns of the resulting DataFrame have different dtypes.
# Pay attention to columns B, E, ad F!
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

### Viewing Data

In [10]:
# Here is how to view the top rows of the frame:
df.head()

            A  B   C  D
2022-01-01  8  6  10  2
2022-01-02  9  8   1  7
2022-01-03  3  9   3  1
2022-01-04  6  3   9  7
2022-01-05  1  1   1  2

In [11]:
# or
df.head(3)

            A  B   C  D
2022-01-01  8  6  10  2
2022-01-02  9  8   1  7
2022-01-03  3  9   3  1

In [12]:
# Here is how to view the bottom rows of the frame:
df.tail(2)

            A  B  C   D
2022-01-05  1  1  1   2
2022-01-06  2  5  9  10

In [ ]:
# Display the index
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# Display the columns
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [13]:
# DataFrame.values gives a NumPy representation of the underlying data
# Note that DataFrame.values does not include the index or column labels in the output
df.values

array([[ 8,  6, 10,  2],
       [ 9,  8,  1,  7],
       [ 3,  9,  3,  1],
       [ 6,  3,  9,  7],
       [ 1,  1,  1,  2],
       [ 2,  5,  9, 10]])

In [14]:
# describe() shows a quick statistic summary of your data:
df.describe()

              A         B         C          D
count  6.000000  6.000000   6.00000   6.000000
mean   4.833333  5.333333   5.50000   4.833333
std    3.311596  3.011091   4.27785   3.656045
min    1.000000  1.000000   1.00000   1.000000
25%    2.250000  3.500000   1.50000   2.000000
50%    4.500000  5.500000   6.00000   4.500000
75%    7.500000  7.500000   9.00000   7.000000
max    9.000000  9.000000  10.00000  10.000000

In [15]:
# Transposing your data:
df.T

   2022-01-01  2022-01-02  2022-01-03  2022-01-04  2022-01-05  2022-01-06
A           8           9           3           6           1           2
B           6           8           9           3           1           5
C          10           1           3           9           1           9
D           2           7           1           7           2          10

In [16]:
# Sorting by an axis:
df.sort_index(axis=1, ascending=False)

             D   C  B  A
2022-01-01   2  10  6  8
2022-01-02   7   1  8  9
2022-01-03   1   3  9  3
2022-01-04   7   9  3  6
2022-01-05   2   1  1  1
2022-01-06  10   9  5  2

In [17]:
# Sorting by values
df.sort_values(by='B')

            A  B   C   D
2022-01-05  1  1   1   2
2022-01-04  6  3   9   7
2022-01-06  2  5   9  10
2022-01-01  8  6  10   2
2022-01-02  9  8   1   7
2022-01-03  3  9   3   1

In [18]:
df.sort_values(by='B', ascending=False)

            A  B   C   D
2022-01-03  3  9   3   1
2022-01-02  9  8   1   7
2022-01-01  8  6  10   2
2022-01-06  2  5   9  10
2022-01-04  6  3   9   7
2022-01-05  1  1   1   2

### SELECTION

In [19]:
# Selecting a single column, which yields a Series, equivalent to df.A:
df['A']

2022-01-01    8
2022-01-02    9
2022-01-03    3
2022-01-04    6
2022-01-05    1
2022-01-06    2
Freq: D, Name: A, dtype: int64

In [20]:
df.A

2022-01-01    8
2022-01-02    9
2022-01-03    3
2022-01-04    6
2022-01-05    1
2022-01-06    2
Freq: D, Name: A, dtype: int64

In [21]:
# Selecting via [], which slices the rows.
df[0:3]

            A  B   C  D
2022-01-01  8  6  10  2
2022-01-02  9  8   1  7
2022-01-03  3  9   3  1

In [22]:
df['20220102':'20220104']

            A  B  C  D
2022-01-02  9  8  1  7
2022-01-03  3  9  3  1
2022-01-04  6  3  9  7

#### Selection by Label

In [23]:
# Remember, we used "dates" as index, e.g. 
# dates = pd.date_range('20220101', periods=6)
# df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

# For getting a cross section using a label:
df.loc[dates[0]]

A     8
B     6
C    10
D     2
Name: 2022-01-01 00:00:00, dtype: int64

In [24]:
df.loc[:, 'A']

2022-01-01    8
2022-01-02    9
2022-01-03    3
2022-01-04    6
2022-01-05    1
2022-01-06    2
Freq: D, Name: A, dtype: int64

In [25]:
# Selecting on a multi-axis by label:
df.loc[:, ['A', 'C']]

            A   C
2022-01-01  8  10
2022-01-02  9   1
2022-01-03  3   3
2022-01-04  6   9
2022-01-05  1   1
2022-01-06  2   9

In [26]:
# Showing label slicing, both endpoints are included:
df.loc['20220102':'20220104', ['A', 'B']]

            A  B
2022-01-02  9  8
2022-01-03  3  9
2022-01-04  6  3

In [ ]:
# Reduction in the dimensions of the returned object:
df.loc['20220102', ['A', 'B']]

A    0.604645
B   -1.698261
Name: 2022-01-02 00:00:00, dtype: float64

In [28]:
# For getting a scalar value:
df.loc[dates[0], 'B']

6

In [29]:
# For getting fast access to a scalar (equivalent to the prior method):
df.at[dates[0], 'A']

8

#### Selection by Position

In [30]:
# Select via the position of the passed integers:
df.iloc[3]

A    6
B    3
C    9
D    7
Name: 2022-01-04 00:00:00, dtype: int64

In [31]:
df

            A  B   C   D
2022-01-01  8  6  10   2
2022-01-02  9  8   1   7
2022-01-03  3  9   3   1
2022-01-04  6  3   9   7
2022-01-05  1  1   1   2
2022-01-06  2  5   9  10

In [32]:
# By integer slices, acting similar to numpy/python:
df.iloc[3:5, 0:2]

            A  B
2022-01-04  6  3
2022-01-05  1  1

In [33]:
# By lists of integer position locations, similar to the numpy/python style:
df.iloc[[1, 2, 4], [0, 2]]

            A  C
2022-01-02  9  1
2022-01-03  3  3
2022-01-05  1  1

In [34]:
# For slicing rows explicitly:
df.iloc[1:3, :]

            A  B  C  D
2022-01-02  9  8  1  7
2022-01-03  3  9  3  1

In [35]:
# For slicing columns explicitly:
df.iloc[:, 1:3]

            B   C
2022-01-01  6  10
2022-01-02  8   1
2022-01-03  9   3
2022-01-04  3   9
2022-01-05  1   1
2022-01-06  5   9

In [36]:
# For getting a value explicitly:
df.iloc[1, 1]

8

In [37]:
# For getting fast access to a scalar (equivalent to the prior method):
# loc: label based indexing
# iloc: position based indexing
# at: works with individuals. label based
# iat: works with individuals. position based
# 
df.iat[1, 1]

8

### Boolean Indexing

In [38]:
# Using a single column’s values to select data.
df[df.A > 4]

            A  B   C  D
2022-01-01  8  6  10  2
2022-01-02  9  8   1  7
2022-01-04  6  3   9  7

In [40]:
# multi boolean conditioning
df[(df.A > 4) & (df.C > 8)]

            A  B   C  D
2022-01-01  8  6  10  2
2022-01-04  6  3   9  7

In [43]:
# Selecting values from a DataFrame where a boolean condition is met
df3 = df[df > 5].copy()
df3

              A    B     C     D
2022-01-01  8.0  6.0  10.0   NaN
2022-01-02  9.0  8.0   NaN   7.0
2022-01-03  NaN  9.0   NaN   NaN
2022-01-04  6.0  NaN   9.0   7.0
2022-01-05  NaN  NaN   NaN   NaN
2022-01-06  NaN  NaN   9.0  10.0

In [44]:
# Using the isin() method for filtering:
df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

            A  B   C   D      E
2022-01-01  8  6  10   2    one
2022-01-02  9  8   1   7    one
2022-01-03  3  9   3   1    two
2022-01-04  6  3   9   7  three
2022-01-05  1  1   1   2   four
2022-01-06  2  5   9  10  three

In [46]:
df2.dtypes

A     int64
B     int64
C     int64
D     int64
E    object
dtype: object

In [47]:
df2[df2['E'].isin(['two', 'four'])]

            A  B  C  D     E
2022-01-03  3  9  3  1   two
2022-01-05  1  1  1  2  four

###  Setting
How to add a new column?

In [48]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20220102', periods=6))
s1

2022-01-02    1
2022-01-03    2
2022-01-04    3
2022-01-05    4
2022-01-06    5
2022-01-07    6
Freq: D, dtype: int64

In [49]:
df['F'] = s1

In [50]:
# note that our original index starts at the 1st day of the month
# however s1 starts at the 2nd day of the month
df

            A  B   C   D    F
2022-01-01  8  6  10   2  NaN
2022-01-02  9  8   1   7  1.0
2022-01-03  3  9   3   1  2.0
2022-01-04  6  3   9   7  3.0
2022-01-05  1  1   1   2  4.0
2022-01-06  2  5   9  10  5.0

In [53]:
# Setting values by label:
df.at[dates[0], 'F'] = 0
# or df.iat[0, 5] = 0
df

            A  B   C  D    F
2022-01-01  8  6  10  5  0.0
2022-01-02  9  8   1  5  1.0
2022-01-03  3  9   3  5  2.0
2022-01-04  6  3   9  5  3.0
2022-01-05  1  1   1  5  4.0
2022-01-06  2  5   9  5  5.0

In [52]:
# Setting by assigning with a NumPy array:
df.loc[:, 'D'] = np.array([5] * len(df))
df

            A  B   C  D    F
2022-01-01  8  6  10  5  0.0
2022-01-02  9  8   1  5  1.0
2022-01-03  3  9   3  5  2.0
2022-01-04  6  3   9  5  3.0
2022-01-05  1  1   1  5  4.0
2022-01-06  2  5   9  5  5.0

## MISSING DATA
Pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [54]:
# Reindexing allows you to change/add/delete the index on a specified axis. 
# This returns a copy of the data.
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.iloc[0,2] = np.NaN
df1

            A  B    C  D    F   E
2022-01-01  8  6  NaN  5  0.0 NaN
2022-01-02  9  8  1.0  5  1.0 NaN
2022-01-03  3  9  3.0  5  2.0 NaN
2022-01-04  6  3  9.0  5  3.0 NaN

In [55]:
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

            A  B    C  D    F    E
2022-01-01  8  6  NaN  5  0.0  1.0
2022-01-02  9  8  1.0  5  1.0  1.0
2022-01-03  3  9  3.0  5  2.0  NaN
2022-01-04  6  3  9.0  5  3.0  NaN

In [57]:
# To drop any rows that have missing data.
df1.dropna(how='any')
# Note that
# how = 'any' ==> If any NA values are present, drop that row or column.
# how = 'all' ==> If all values are NA, drop that row or column.

            A  B    C  D    F    E
2022-01-02  9  8  1.0  5  1.0  1.0

In [58]:
# Drop the columns where at least one element is missing
df1.dropna(axis='columns')

            A  B  D    F
2022-01-01  8  6  5  0.0
2022-01-02  9  8  5  1.0
2022-01-03  3  9  5  2.0
2022-01-04  6  3  5  3.0

In [59]:
# Keep only the rows with at least 4 non-NA values.
df1.dropna(thresh=4)
# note that the threshold is not for the number of NaNs
# instead, it is for the number of non-NaNs

            A  B    C  D    F    E
2022-01-01  8  6  NaN  5  0.0  1.0
2022-01-02  9  8  1.0  5  1.0  1.0
2022-01-03  3  9  3.0  5  2.0  NaN
2022-01-04  6  3  9.0  5  3.0  NaN

In [60]:
# To remove the rows, where a specific column has NaNs
df1.dropna(subset=['F'])

            A  B    C  D    F    E
2022-01-01  8  6  NaN  5  0.0  1.0
2022-01-02  9  8  1.0  5  1.0  1.0
2022-01-03  3  9  3.0  5  2.0  NaN
2022-01-04  6  3  9.0  5  3.0  NaN

In [61]:
# Filling missing data.
df1.fillna(value=-999)

            A  B      C  D    F      E
2022-01-01  8  6 -999.0  5  0.0    1.0
2022-01-02  9  8    1.0  5  1.0    1.0
2022-01-03  3  9    3.0  5  2.0 -999.0
2022-01-04  6  3    9.0  5  3.0 -999.0

In [62]:
# To get the boolean mask where values are nan.
pd.isna(df1)

             A   B   C   D   F   E
2022-01-01 NaN NaN NaN NaN NaN NaN
2022-01-02 NaN NaN NaN NaN NaN NaN
2022-01-03 NaN NaN NaN NaN NaN NaN
2022-01-04 NaN NaN NaN NaN NaN NaN

In [ ]:
# In R "na" and "null" are two separate things, but not in python
# so you can also use pd.isnull(), instead of pd.isna()
pd.isnull(df1)

                A      B      C      D      F      E
2022-01-01  False  False   True  False   True  False
2022-01-02  False  False  False  False  False  False
2022-01-03  False  False  False  False  False   True
2022-01-04  False  False  False  False  False   True

## Operations

### Statistics

In [64]:
# Performing a descriptive statistic:
# average of columns
df.mean()

A    4.833333
B    5.333333
C    5.500000
D    5.000000
F    2.500000
dtype: float64

In [65]:
# average of rows (simply by setting axis to 1)
df.mean(1)

2022-01-01    5.8
2022-01-02    4.8
2022-01-03    4.4
2022-01-04    5.2
2022-01-05    2.4
2022-01-06    5.2
Freq: D, dtype: float64

In [ ]:
# Operating with objects that have different dimensionality and need alignment. 
# In addition, pandas automatically broadcasts along the specified dimension.
dates = pd.date_range('20220101', periods=6)
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
s

2022-01-01    NaN
2022-01-02    NaN
2022-01-03    1.0
2022-01-04    3.0
2022-01-05    5.0
2022-01-06    NaN
Freq: D, dtype: float64

In [ ]:
# Above, when we shift index, 1st of month becomes 3rd, 2nd becomes 4th, etc.
# but since we don't have 7th and 8th in our index, when they are shifted,
# 1st and 2nd elements become NaN

In [67]:
df = pd.DataFrame(np.random.randint(1,11, size=(6, 4)), index=dates, columns=list('ABCD'))
df

             A   B  C  D
2022-01-01   1   6  6  6
2022-01-02   7   9  5  1
2022-01-03   3   2  1  5
2022-01-04  10   4  7  2
2022-01-05   4   2  1  9
2022-01-06   8  10  3  9

In [68]:
s = pd.Series([1, 3, 5, -2, 6, 8], index=dates)

In [69]:
# dataframe.sub: Subtraction of dataframe and other, element-wise (binary operator sub).
df.sub(s, axis='index')

             A  B  C  D
2022-01-01   0  5  5  5
2022-01-02   4  6  2 -2
2022-01-03  -2 -3 -4  0
2022-01-04  12  6  9  4
2022-01-05  -2 -4 -5  3
2022-01-06   0  2 -5  1

### Apply

In [70]:
df

             A   B  C  D
2022-01-01   1   6  6  6
2022-01-02   7   9  5  1
2022-01-03   3   2  1  5
2022-01-04  10   4  7  2
2022-01-05   4   2  1  9
2022-01-06   8  10  3  9

In [71]:
# dataframe.cumsum returns cumulative sum over a DataFrame or Series axis.
#
# cumulative sum - vertical
df.apply(np.cumsum)

             A   B   C   D
2022-01-01   1   6   6   6
2022-01-02   8  15  11   7
2022-01-03  11  17  12  12
2022-01-04  21  21  19  14
2022-01-05  25  23  20  23
2022-01-06  33  33  23  32

In [72]:
# cumulative sum - horizontal
df.apply(np.cumsum,axis=1)

             A   B   C   D
2022-01-01   1   7  13  19
2022-01-02   7  16  21  22
2022-01-03   3   5   6  11
2022-01-04  10  14  21  23
2022-01-05   4   6   7  16
2022-01-06   8  18  21  30

In [73]:
# finding range manually is also easy
df.apply(lambda x: x.max() - x.min())

A    9
B    8
C    6
D    8
dtype: int64

In [74]:
# finding range of rows
df.T.apply(lambda x: x.max() - x.min())

2022-01-01    5
2022-01-02    8
2022-01-03    4
2022-01-04    8
2022-01-05    8
2022-01-06    7
Freq: D, dtype: int64

In [75]:
# let's do a column-wise operating
df['A'] = df['A'].apply(lambda x: x/10)
df

              A   B  C  D
2022-01-01  0.1   6  6  6
2022-01-02  0.7   9  5  1
2022-01-03  0.3   2  1  5
2022-01-04  1.0   4  7  2
2022-01-05  0.4   2  1  9
2022-01-06  0.8  10  3  9

## MERGING
Pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

#### CONCAT

In [76]:
df = pd.DataFrame(np.random.randint(1,11, size=(6, 6)))
df

   0   1  2   3   4  5
0  9  10  5   2  10  6
1  2  10  8   8   6  8
2  5   6  3   2   4  2
3  4  10  4   3   3  2
4  5   8  7   3   5  7
5  2   4  4  10   1  5

In [77]:
# break it into pieces
piece1 = df[1:4]
piece2 = df[3:6]
piece1

   0   1  2  3  4  5
1  2  10  8  8  6  8
2  5   6  3  2  4  2
3  4  10  4  3  3  2

In [78]:
piece2

   0   1  2   3  4  5
3  4  10  4   3  3  2
4  5   8  7   3  5  7
5  2   4  4  10  1  5

In [79]:
# First, let's try this
pd.concat([piece1,piece2])

   0   1  2   3  4  5
1  2  10  8   8  6  8
2  5   6  3   2  4  2
3  4  10  4   3  3  2
3  4  10  4   3  3  2
4  5   8  7   3  5  7
5  2   4  4  10  1  5

In [ ]:
# Realize the repeat above!
# let's try this now

In [82]:
pd.concat([piece1, piece2], ignore_index=True)

   0   1  2   3  4  5
0  2  10  8   8  6  8
1  5   6  3   2  4  2
2  4  10  4   3  3  2
3  4  10  4   3  3  2
4  5   8  7   3  5  7
5  2   4  4  10  1  5

#### JOIN
SQL style merges

In [85]:
sales2020 = pd.DataFrame({'Model': ['Levis501', 'Levis550'], '2020 Sales': [15130, 10232]})
sales2020

      Model  2020 Sales
0  Levis501       15130
1  Levis550       10232

In [86]:
sales2021 = pd.DataFrame({'Model': ['Levis501', 'Levis550'], '2021 Sales': [16328, 12034]})
sales2021

      Model  2021 Sales
0  Levis501       16328
1  Levis550       12034

In [88]:
pd.merge(sales2020,sales2021, on='Model')

      Model  2020 Sales  2021 Sales
0  Levis501       15130       16328
1  Levis550       10232       12034

### APPEND

In [89]:
# Append rows to a dataframe
df = pd.DataFrame(np.random.randint(1,10,size=(8, 4)), columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  6  9  9
1  8  4  9  8
2  8  6  3  5
3  6  8  8  3
4  7  6  5  9
5  2  9  9  4
6  2  5  9  1
7  3  8  8  8

In [91]:
# Let's add a row to the end 
# note how we get get the column names of the original df
s = pd.DataFrame(np.random.randint(1,10,size=(1, 4)), columns=df.columns.values)
df.append(s, ignore_index=True)

   A  B  C  D
0  6  6  9  9
1  8  4  9  8
2  8  6  3  5
3  6  8  8  3
4  7  6  5  9
5  2  9  9  4
6  2  5  9  1
7  3  8  8  8
8  3  7  3  2

## GROUPING

In [ ]:
# By “group by” we are referring to a process involving one or more of the following steps:
# (a) Splitting the data into groups based on some criteria
# (b) Applying a function to each group independently
# (c) Combining the results into a data structure

In [95]:
df = pd.DataFrame({'A': ['UMBC', 'UMD', 'GW', 'Duke',
                         'UMBC', 'UMD', 'GW', 'Duke'],
                   'B': ['ugrad', 'ugrad', 'ugrad', 'ugrad',
                         'grad', 'grad', 'grad', 'grad'],
                   'C': np.random.randint(50,101,8),
                   'D': np.random.randint(50,101,8)})
df

      A      B   C   D
0  UMBC  ugrad  51  59
1   UMD  ugrad  75  93
2    GW  ugrad  56  89
3  Duke  ugrad  83  67
4  UMBC   grad  60  64
5   UMD   grad  74  89
6    GW   grad  50  67
7  Duke   grad  87  81

In [96]:
# Grouping and then applying the sum() function to the resulting groups.
df.groupby('A').sum()

        C    D
A
Duke  170  148
GW    106  156
UMBC  111  123
UMD   149  182

In [97]:
# Grouping by multiple columns forms a hierarchical index,
# and again we can apply the sum function.
df.groupby(['A', 'B']).sum()

             C   D
A    B
Duke grad   87  81
     ugrad  83  67
GW   grad   50  67
     ugrad  56  89
UMBC grad   60  64
     ugrad  51  59
UMD  grad   74  89
     ugrad  75  93

### Let's Melt!!
Assume the dataframe below shows the performance of devices (with varying width, length, and thickness) in the last two columns.

How can we transform this dataframe so that it will list the performance of all devices in the following format: 

width, length, thickness, performance

In [98]:
df = pd.DataFrame({'Width': {1: 11, 2: 12, 3: 15},
                   'Length': {1: 1, 2: 3, 3: 5},
                   'Thick_1m': {1: 2, 2: 4, 3: 6},
                   'Thick_2m': {1: 2.5, 2: 4.1, 3: 6.2}})
df

   Width  Length  Thick_1m  Thick_2m
1     11       1         2       2.5
2     12       3         4       4.1
3     15       5         6       6.2

In [99]:
# For this transformation, we need "MELT"
df2 = df.melt(id_vars=["Width", "Length"], 
        var_name="Thickness", 
        value_name="performance").dropna().copy()
df2

   Width  Length Thickness  performance
0     11       1  Thick_1m          2.0
1     12       3  Thick_1m          4.0
2     15       5  Thick_1m          6.0
3     11       1  Thick_2m          2.5
4     12       3  Thick_2m          4.1
5     15       5  Thick_2m          6.2

In [100]:
df2["Thickness"] = df2["Thickness"].str.replace("Thick_","").copy()
df2["Thickness"] = df2["Thickness"].str.replace("m","").astype(float).copy()
df2

   Width  Length  Thickness  performance
0     11       1        1.0          2.0
1     12       3        1.0          4.0
2     15       5        1.0          6.0
3     11       1        2.0          2.5
4     12       3        2.0          4.1
5     15       5        2.0          6.2

## Multi-Indexing

In [101]:
# We want to get a dataframe which will list grad and undergrad student numbers of 4 universities
# Let's create pairs first
list1 = np.repeat(np.asarray(['UMBC', 'UMD', 'Umass','Duke']).T, 2, axis=0).tolist()
list2 = ['Grad', 'Undergrad']*4
tuples = list(zip(*[list1,list2]))
print(tuples)

[('UMBC', 'Grad'), ('UMBC', 'Undergrad'), ('UMD', 'Grad'), ('UMD', 'Undergrad'), ('Umass', 'Grad'), ('Umass', 'Undergrad'), ('Duke', 'Grad'), ('Duke', 'Undergrad')]

In [102]:
index = pd.MultiIndex.from_tuples(tuples, names=['University', 'Type'])
df = pd.DataFrame(np.random.randint(1000,10000, size=(8, 2)), index=index, columns=['Domestic', 'International'])
df

                      Domestic  International
University Type
UMBC       Grad           4447           1794
           Undergrad      2481           6647
UMD        Grad           2422           9606
           Undergrad      6152           2158
Umass      Grad           8702           4764
           Undergrad      7198           3467
Duke       Grad           8833           7354
           Undergrad      3160           6279

In [ ]:
df2 = df[:4]
df2

                      Domestic  International
University Type
UMBC       Grad           7412           1259
           Undergrad      3924           8769
UMD        Grad           3430           2057
           Undergrad      1548           8656

In [103]:
df.loc['UMBC']

           Domestic  International
Type
Grad           4447           1794
Undergrad      2481           6647

In [104]:
# Let's get number of students at UMBC
df.loc['UMBC','Grad']

Domestic         4447
International    1794
Name: (UMBC, Grad), dtype: int64

In [105]:
# Let's get number of domestic students at UMBC
df.loc['UMBC','Grad']['Domestic']
# or df.loc['UMBC','Grad'][0]

4447

#### STACK
<b>stack</b> inserts a list into the inner index <br>
<b>melt</b> inserts that list as a new column called 'variable' (can be renamed)

In [106]:
# The stack() method “compresses” a level in the DataFrame’s columns.
stacked = df.stack()
stacked

University  Type
UMBC        Grad       Domestic         4447
                       International    1794
            Undergrad  Domestic         2481
                       International    6647
UMD         Grad       Domestic         2422
                       International    9606
            Undergrad  Domestic         6152
                       International    2158
Umass       Grad       Domestic         8702
                       International    4764
            Undergrad  Domestic         7198
                       International    3467
Duke        Grad       Domestic         8833
                       International    7354
            Undergrad  Domestic         3160
                       International    6279
dtype: int64

In [107]:
# With a “stacked” DataFrame or Series (having a MultiIndex as the index), 
# the inverse operation of stack() is unstack(), which by default unstacks the last level:
stacked.unstack()

                      Domestic  International
University Type
Duke       Grad           8833           7354
           Undergrad      3160           6279
UMBC       Grad           4447           1794
           Undergrad      2481           6647
UMD        Grad           2422           9606
           Undergrad      6152           2158
Umass      Grad           8702           4764
           Undergrad      7198           3467

In [108]:
### Reshaping via unstuck
# Watch carefully what happens now!
stacked.unstack(1)

Type                      Grad  Undergrad
University
Duke       Domestic       8833       3160
           International  7354       6279
UMBC       Domestic       4447       2481
           International  1794       6647
UMD        Domestic       2422       6152
           International  9606       2158
Umass      Domestic       8702       7198
           International  4764       3467

In [ ]:
# Remember stacked
stacked

University  Type
UMBC        Grad       Domestic         7412
                       International    1259
            Undergrad  Domestic         3924
                       International    8769
UMD         Grad       Domestic         3430
                       International    2057
            Undergrad  Domestic         1548
                       International    8656
Umass       Grad       Domestic         6307
                       International    6538
            Undergrad  Domestic         8199
                       International    3081
Duke        Grad       Domestic         9967
                       International    2704
            Undergrad  Domestic         9681
                       International    4950
dtype: int64

In [109]:
# let's reshape according to the main index
stacked.unstack(0)

University               Duke  UMBC   UMD  Umass
Type
Grad      Domestic       8833  4447  2422   8702
          International  7354  1794  9606   4764
Undergrad Domestic       3160  2481  6152   7198
          International  6279  6647  2158   3467

### PIVOT TABLES

In [111]:
# Let's say we have number of sales for two different products (D and E)
# at four different stores
# by three different managers
# we divide number of sales in two groups: the ones made in week days (M-F)
# and the ones made in weekends (SS)
# managers work either in week days or in weekends but not both
df = pd.DataFrame({'A': ['Store-1', 'Store-2', 'Store-3', 'Store-4'] * 3,
                   'B': ['Manager-1', 'Manager-2', 'Manager-3'] * 4,
                   'C': ['M-F', 'M-F', 'M-F', 'SS', 'SS', 'SS'] * 2,
                   'D': np.random.randint(1,13,12),
                   'E': np.random.randint(1,31,12)})
df

          A          B    C   D   E
0   Store-1  Manager-1  M-F   7  17
1   Store-2  Manager-2  M-F   2  14
2   Store-3  Manager-3  M-F   9  30
3   Store-4  Manager-1   SS   5  13
4   Store-1  Manager-2   SS   6   9
5   Store-2  Manager-3   SS   4  22
6   Store-3  Manager-1  M-F   8  13
7   Store-4  Manager-2  M-F   2  14
8   Store-1  Manager-3  M-F   5  10
9   Store-2  Manager-1   SS  12   8
10  Store-3  Manager-2   SS   8  24
11  Store-4  Manager-3   SS   2  10

In [112]:
# We can produce pivot tables from this data very easily:
# Let's see which manager sold how many "product Ds" in each store
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])

C                  M-F    SS
A       B
Store-1 Manager-1  7.0   NaN
        Manager-2  NaN   6.0
        Manager-3  5.0   NaN
Store-2 Manager-1  NaN  12.0
        Manager-2  2.0   NaN
        Manager-3  NaN   4.0
Store-3 Manager-1  8.0   NaN
        Manager-2  NaN   8.0
        Manager-3  9.0   NaN
Store-4 Manager-1  NaN   5.0
        Manager-2  2.0   NaN
        Manager-3  NaN   2.0

In [113]:
# Example 2
# Let's say we have number of people 
# as functions of blood type, RH+ or -
# in three towns
df = pd.DataFrame({
    'Type': np.repeat(np.asarray(['A', 'B', 'AB','0']).T, 4, axis=0),
    'RH': [1,-1]*8,
    'M/F': ['Male','Male','Female','Female']*4,
    'D': np.random.randint(10000,20000,16)})

In [ ]:
df

   Type  RH     M/F      D
0     A   1    Male  18772
1     A  -1    Male  10352
2     A   1  Female  13687
3     A  -1  Female  12978
4     B   1    Male  18619
5     B  -1    Male  18191
6     B   1  Female  18182
7     B  -1  Female  16249
8    AB   1    Male  19348
9    AB  -1    Male  14570
10   AB   1  Female  13361
11   AB  -1  Female  13107
12    0   1    Male  18184
13    0  -1    Male  17579
14    0   1  Female  12639
15    0  -1  Female  12636

In [114]:
# Let's find out the total number of people 
pd.pivot_table(df,values='D',index=['Type','RH'], columns=['M/F'])

M/F      Female   Male
Type RH
0    -1   18887  11214
      1   12301  15100
A    -1   11234  15837
      1   11100  14803
AB   -1   18919  16892
      1   12849  12197
B    -1   12712  13251
      1   17963  17845

## GETTING DATA IN/OUT

### CSV

In [ ]:
# Writing to a csv file
df.to_csv('data601_lecture04.csv')

In [ ]:
# Reading from a csv file.
pd.read_csv('data601_lecture04.csv')

    Unnamed: 0 Type  RH     M/F      D
0            0    A   1    Male  18772
1            1    A  -1    Male  10352
2            2    A   1  Female  13687
3            3    A  -1  Female  12978
4            4    B   1    Male  18619
5            5    B  -1    Male  18191
6            6    B   1  Female  18182
7            7    B  -1  Female  16249
8            8   AB   1    Male  19348
9            9   AB  -1    Male  14570
10          10   AB   1  Female  13361
11          11   AB  -1  Female  13107
12          12    0   1    Male  18184
13          13    0  -1    Male  17579
14          14    0   1  Female  12639
15          15    0  -1  Female  12636

### Excel

In [ ]:
# Writing to an excel file.
df.to_excel('data601_lecture04.xlsx', sheet_name='Sheet1')

In [ ]:
# Reading from an excel file.
pd.read_excel('data601_lecture04.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

    Unnamed: 0 Type  RH     M/F      D
0            0    A   1    Male  18772
1            1    A  -1    Male  10352
2            2    A   1  Female  13687
3            3    A  -1  Female  12978
4            4    B   1    Male  18619
5            5    B  -1    Male  18191
6            6    B   1  Female  18182
7            7    B  -1  Female  16249
8            8   AB   1    Male  19348
9            9   AB  -1    Male  14570
10          10   AB   1  Female  13361
11          11   AB  -1  Female  13107
12          12    0   1    Male  18184
13          13    0  -1    Male  17579
14          14    0   1  Female  12639
15          15    0  -1  Female  12636